# Generated by Django 3.1.13 on 2022-07-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scummy', '0002_order_delivery_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('enquiry', 'Enquiry'), ('complaint', 'Complaint'), ('report', 'Report'), ('others', 'Others')], max_length=20)),
                ('email', models.EmailField(max_length=150)),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
