# Generated by Django 3.1.13 on 2022-07-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scummy', '0007_auto_20220724_0904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='items',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='balance',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='amount_paid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
