# Generated by Django 3.1.13 on 2022-07-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scummy', '0008_auto_20220724_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='packed',
            field=models.BooleanField(default=False),
        ),
    ]
