# Generated by Django 3.1.13 on 2022-08-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scummy', '0009_order_packed'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/images'),
        ),
    ]
