# Generated by Django 3.1.13 on 2022-08-17 13:36

from django.db import migrations
import scummy.managers


class Migration(migrations.Migration):

    dependencies = [
        ('scummy', '0010_charge_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=scummy.managers.LowercaseEmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
