# Generated by Django 3.1.13 on 2022-08-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scummy', '0011_auto_20220817_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
