# Generated by Django 3.1.13 on 2022-08-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scummy', '0012_order_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dispatch_partner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
