# Generated by Django 3.1.13 on 2022-08-18 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scummy', '0013_order_dispatch_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatcherperDestination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='scummy.destinationcharge')),
            ],
        ),
    ]
